[build-system]
requires = ["setuptools>=61.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "xan"
version = "0.0.02"
authors = [
  { name="Taha Shieenavaz", email="tahashieenavaz@gmail.com" },
]
description = "Introduces a command to add every function and class to __init__ files recursively."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["fire"]
keywords = ["productivity", "init", "python packaging", "package", "setuptools"]
license = { file = "LICENSE" }
urls = { Homepage="https://github.com/tahashieenavaz/xan", Repository="https://github.com/tahashieenavaz/xan", Documentation="https://github.com/tahashieenavaz/xan#readme" }

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "docs*"]

[tool.setuptools.package-data]
xan = ["*.md", "*.txt", "*.png"]

[project.scripts]
xan = "xan.main:main"